services:
    mysqldb:
        container_name: mysqlcontainer
        image: mysql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: patientsdb
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3307:3306
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            springboot-mysql-net:
                
    patient-service:
        container_name: patient-service
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 9001:9001
        depends_on:
            - mysqldb
        environment:
            - SPRING_APPLICATION_JSON={"server":{"port":9001,"address":"0.0.0.0"}}
            - spring.jpa.hibernate.ddl-auto=update
            - spring.datasource.url=jdbc:mysql://mysqlcontainer:3306/patientsdb
            - spring.datasource.username=user
            - spring.datasource.password=user
            - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver      
        
        networks:
            springboot-mysql-net:
        restart: on-failure
        
networks:
    springboot-mysql-net: