server: 
    port: 1919
    
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: PATIENT-SERVICE
                          uri: lb://PATIENT-SERVICE
                          predicates:
                              - Path=/patients/**
                        - id: DRUG-SERVICE
                          uri: lb://DRUG-SERVICE
                          predicates:
                              - Path=/drugs/**

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost